/**
 * SDK Reference: content/sdk, generated by `npm run gen:sdk` (scripts/sdk-docs) and built
 * separately as a static export (scripts/build-sdk.mjs), so its ~2,000 pages stay out of the
 * main site's Worker bundle. Only the *.sdk.tsx routes import this.
 */
import { createElement } from 'react';
import { llms, loader } from 'fumadocs-core/source';
import type * as PageTree from 'fumadocs-core/page-tree';
import { SdkKindIcon, isSdkKind } from '@/components/sdk-kind-icon';
import { defineDocs } from 'fumadocs-mdx/macro';
import { metaSchema, pageSchema } from 'fumadocs-core/source/schema';
import { applyMdxPreset } from 'fumadocs-mdx/config';
import { remarkBasePath } from './remark-base-path';

const docs = defineDocs({
  dir: 'content/sdk',
  docs: {
    schema: pageSchema,
    // Keeps the default fumadocs preset (a collection-level mdxOptions would replace it)
    mdxOptions: applyMdxPreset({ remarkPlugins: (v) => [...v, remarkBasePath] }),
    postprocess: {
      includeProcessedMarkdown: true,
    },
  },
  meta: {
    schema: metaSchema,
  },
});

/**
 * TypeDoc reuses file names across modules (index, same-named classes per chain), so pages keep
 * their folder paths. The @sentio/sdk group is the tab root and its root-exports folder is not a
 * URL segment: sentio-sdk/root/classes/Counter -> /sdk/classes/Counter,
 * typemove/aptos/index -> /sdk/typemove/aptos
 */
function sdkSlugs(file: { path: string }): string[] {
  let segs = file.path.replace(/\.mdx?$/, '').split('/');
  if (segs[0] === 'sentio-sdk') segs = segs[1] === 'root' ? segs.slice(2) : segs.slice(1);
  if (segs[segs.length - 1] === 'index') segs = segs.slice(0, -1);
  return segs;
}

export const sdkSource = loader({
  baseUrl: '/sdk',
  source: docs.toFumadocsSource(),
  slugs: sdkSlugs,
  // Frontmatter `icon` is the declaration kind (class, function, ...); folders take their index's
  icon: (kind) => (kind && isSdkKind(kind) ? createElement(SdkKindIcon, { kind }) : undefined),
});

/** The page's markdown, written by app/llms.mdx/sdk/[[...slug]]/route.sdk.ts */
export function sdkMarkdownUrl(page: { slugs: string[] }) {
  return `/llms.mdx/sdk/${[...page.slugs, 'content.md'].join('/')}`;
}

export const sdkLlms = llms(sdkSource, {
  renderPage: async (page) => `# ${page.data.title}

${await page.data.getText('processed')}`,
});

/** A module with nothing but its own page (e.g. core) is listed as that page, not an empty folder */
function foldLoneIndexes<T extends PageTree.Root | PageTree.Folder>(node: T): T {
  return {
    ...node,
    children: node.children.map((child) => {
      if (child.type !== 'folder') return child;
      if (child.index && child.children.length === 0) return child.index;
      return foldLoneIndexes(child);
    }),
  };
}

let fullTree: PageTree.Root | undefined;

/** The whole SDK tree; app/sdk/tree.json/route.sdk.ts serves it to the sidebar after the first paint */
export function sdkFullTree(): PageTree.Root {
  fullTree ??= foldLoneIndexes(sdkSource.getPageTree());
  return fullTree;
}

function contains(node: PageTree.Node, url: string): boolean {
  if (node.type === 'page') return node.url === url;
  if (node.type !== 'folder') return false;
  return node.index?.url === url || node.children.some((child) => contains(child, url));
}

function firstPage(folder: PageTree.Folder): PageTree.Item | undefined {
  for (const child of folder.children) {
    if (child.type === 'page') return child;
    if (child.type === 'folder') {
      const page = child.index ?? firstPage(child);
      if (page) return page;
    }
  }
}

function expand(folder: PageTree.Folder, url: string): PageTree.Folder {
  return {
    ...folder,
    children: folder.children.map((child) => {
      if (child.type !== 'folder') return child;
      if (contains(child, url)) return expand(child, url);
      // Collapsed: no children until components/sdk-docs-shell.tsx loads the whole tree; before
      // that, its title opens its index page, or its first page, where it is expanded
      return { ...child, children: [], index: child.index ?? firstPage(child) };
    }),
  };
}

/**
 * The page tree rendered with the page at `url`: the top-level groups with their direct items,
 * expanded along the path to the page. The whole tree (~2,400 nodes) would be serialized into
 * every page (~5 MB each); the browser loads it once instead (sdkFullTree), the way TypeDoc's HTML
 * loads its navigation separately.
 */
export function sdkTreeFor(url: string): PageTree.Root {
  const tree = sdkFullTree();
  return {
    ...tree,
    // fumadocs' tree context only takes a new tree when its $id changes
    $id: `${tree.$id}:${url}`,
    children: tree.children.map((child) => (child.type === 'folder' ? expand(child, url) : child)),
  };
}
