name: Vale
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
